version: '3'
services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - 61616:61616   # OpenWire
      - 8161:8161     # Web Console
    volumes:
      - activemq-data:/var/lib/activemq/data
    networks:
      - stattauto
  kundenservice:
    image: hermannw/kundenservice:0.1.0
    container_name: kundenservice
    ports:
      - 8081:8081
    networks:
      - stattauto

volumes:
  activemq-data:
    driver: local

networks:
  stattauto:
    driver: bridge
